### ISSUE TITLE
Add conditional compilation via Cargo features

### ISSUE THREAD

**Issue by gerred** [gerred/prime-iroh#7]
## Overview
Implement conditional compilation using Cargo features to control which backends are included in the build.

Parent Issue: #1

## Current State
- All code is compiled regardless of backend usage
- No way to exclude unnecessary dependencies
- Binary size includes all backends

### Cargo.toml Configuration
```toml
[package]
name = "prime-iroh"
version = "0.3.0"
edition = "2021"

[dependencies]
# Core dependencies
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
env_logger = "0.10"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }

# Backend-specific dependencies (optional)
iroh-quinn = { version = "0.13", optional = true }
cudarc = { version = "0.16", optional = true }
nixl-sys = { version = "0.2", optional = true }

# Python bindings
pyo3 = { version = "0.19", features = ["extension-module"], optional = true }

[features]
default = ["quic", "python"]

# Individual backends
quic = ["dep:iroh-quinn"]
nccl = ["dep:cudarc", "cudarc/nccl"]
nixl = ["dep:nixl-sys"]

# Python bindings
python = ["dep:pyo3"]

# Development features
full = ["quic", "nccl", "nixl", "python"]
bench = ["full"]

# Build configurations
static = []
dynamic = []

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tokio-test = "0.4"

[[bench]]
name = "transport_benchmarks"
harness = false
required-features = ["bench"]
```

### Backend Module Organization
```rust
// src/backend/mod.rs
pub mod common;
pub mod registry;

#[cfg(feature = "quic")]
pub mod quic;

#[cfg(feature = "nccl")]
pub mod nccl;

#[cfg(feature = "nixl")]
pub mod nixl;

// Re-exports based on features
#[cfg(feature = "quic")]
pub use quic::{QuicBackend, QuicBackendFactory};

#[cfg(feature = "nccl")]
pub use nccl::{NcclBackend, NcclBackendFactory};

#[cfg(feature = "nixl")]
pub use nixl::{NixlBackend, NixlBackendFactory};
```

### Conditional Backend Registration
```rust
// src/backend/registry.rs
use once_cell::sync::Lazy;

static REGISTRY: Lazy<Arc<Mutex<BackendRegistry>>> = Lazy::new(|| {
    let mut registry = BackendRegistry::new();
    
    #[cfg(feature = "quic")]
    {
        registry.register_factory(
            BackendType::Quic,
            QuicBackendFactory::new()
        ).expect("Failed to register QUIC backend");
    }
    
    #[cfg(feature = "nccl")]
    {
        if nccl::is_available() {
            registry.register_factory(
                BackendType::Nccl,
                NcclBackendFactory::new()
            ).expect("Failed to register NCCL backend");
        }
    }
    
    #[cfg(feature = "nixl")]
    {
        if nixl::is_available() {
            registry.register_factory(
                BackendType::Nixl,
                NixlBackendFactory::new()
            ).expect("Failed to register NIXL backend");
        }
    }
    
    Arc::new(Mutex::new(registry))
});
```

### Feature-Gated Implementation
```rust
// src/backend/auto_detect.rs
pub fn auto_detect_backend() -> Result<BackendType> {
    let mut candidates = Vec::new();
    
    #[cfg(feature = "nccl")]
    {
        if check_nccl_availability() {
            candidates.push(BackendType::Nccl);
        }
    }
    
    #[cfg(feature = "nixl")]
    {
        if check_nixl_availability() {
            candidates.push(BackendType::Nixl);
        }
    }
    
    #[cfg(feature = "quic")]
    {
        // QUIC is always available when the feature is enabled
        candidates.push(BackendType::Quic);
    }
    
    if candidates.is_empty() {
        return Err(BackendError::NoBackendAvailable);
    }
    
    // Score and select best candidate
    select_best_backend(candidates)
}
```

### Python Bindings Conditional Compilation
```rust
// src/python/mod.rs
#[cfg(feature = "python")]
use pyo3::prelude::*;

#[cfg(feature = "python")]
#[pyclass]
pub struct PyNode {
    inner: Node,
}

#[cfg(feature = "python")]
#[pymethods]
impl PyNode {
    #[new]
    fn new(backend: Option<String>) -> PyResult<Self> {
        let backend_type = match backend.as_deref() {
            #[cfg(feature = "nccl")]
            Some("nccl") => BackendType::Nccl,
            #[cfg(feature = "nixl")]
            Some("nixl") => BackendType::Nixl,
            #[cfg(feature = "quic")]
            Some("quic") => BackendType::Quic,
            Some("auto") | None => auto_detect_backend()
                .map_err(|e| PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(
                    format!("Failed to auto-detect backend: {}", e)
                ))?,
            Some(unknown) => return Err(PyErr::new::<pyo3::exceptions::PyValueError, _>(
                format!("Unknown backend: {}", unknown)
            )),
        };
        
        Ok(Self {
            inner: Node::new(backend_type)?,
        })
    }
    
    fn available_backends(&self) -> Vec<String> {
        let mut backends = Vec::new();
        
        #[cfg(feature = "quic")]
        backends.push("quic".to_string());
        
        #[cfg(feature = "nccl")]
        if check_nccl_availability() {
            backends.push("nccl".to_string());
        }
        
        #[cfg(feature = "nixl")]
        if check_nixl_availability() {
            backends.push("nixl".to_string());
        }
        
        backends
    }
}

#[cfg(feature = "python")]
#[pymodule]
fn prime_iroh(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<PyNode>()?;
    Ok(())
}
```

### Build Script for Feature Detection
```rust
// build.rs
use std::env;

fn main() {
    // Validate feature combinations
    let features = env::vars()
        .filter(|(k, _)| k.starts_with("CARGO_FEATURE_"))
        .map(|(k, _)| k.strip_prefix("CARGO_FEATURE_").unwrap().to_lowercase())
        .collect::<Vec<_>>();
    
    // Ensure at least one backend is enabled
    let has_backend = features.iter().any(|f| 
        f == "quic" || f == "nccl" || f == "nixl"
    );
    
    if !has_backend && !features.contains(&"full".to_string()) {
        println!("cargo:warning=No backend features enabled. Consider enabling 'quic', 'nccl', 'nixl', or 'full'");
    }
    
    // Set build-time configuration
    #[cfg(feature = "nccl")]
    {
        // Link NCCL library
        if let Ok(cuda_path) = env::var("CUDA_PATH") {
            println!("cargo:rustc-link-search=native={}/lib64", cuda_path);
            println!("cargo:rustc-link-lib=nccl");
        }
    }
    
    #[cfg(feature = "nixl")]
    {
        // Configure NIXL build
        if let Ok(nixl_path) = env::var("NIXL_PATH") {
            println!("cargo:rustc-link-search=native={}/lib", nixl_path);
        }
    }
}
```

### Documentation for Features
```markdown
# Cargo Features

## Backend Features
- `quic` (default): Enables QUIC/Iroh backend for universal network support
- `nccl`: Enables NCCL backend for NVIDIA GPU communication
- `nixl`: Enables NIXL backend for heterogeneous memory support

## Binding Features
- `python` (default): Enables Python bindings via PyO3

## Meta Features
- `full`: Enables all backends and bindings
- `bench`: Enables benchmarking support (includes `full`)

## Build Examples

### Minimal build (QUIC only)
```bash
cargo build --no-default-features --features quic
```

### GPU-only build
```bash
cargo build --no-default-features --features nccl
```

### Full build
```bash
cargo build --features full
```

### Python package with specific backends
```bash
maturin build --features "python,quic,nccl"
```
```

## Testing Strategy

- [ ] Test each feature combination in CI
- [ ] Verify conditional compilation works correctly
- [ ] Test that disabled backends aren't accessible
- [ ] Benchmark binary size differences
- [ ] Test Python bindings with different features

## Acceptance Criteria

- [ ] Features control which code is compiled
- [ ] Binary size reduced when features disabled
- [ ] No runtime errors from missing features
- [ ] Documentation clearly explains features
- [ ] CI tests all important feature combinations
- [ ] Python bindings work with any backend combination

## References

- Cargo Features Documentation
- Conditional Compilation in Rust
- PyO3 Feature Flags
